use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    tauri_build::build();

    // Embed all data JSON files from the workspace root.
    // The workspace root is two levels above src-tauri/  (SoLaWi/)
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let workspace_root = manifest_dir
        .parent()                   // ernte-app/
        .and_then(|p| p.parent())   // SoLaWi/
        .map(|p| p.to_path_buf())
        .unwrap_or_else(|| PathBuf::from("."));

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let gen_path = out_dir.join("embedded_historie.rs");

    let mut entries: Vec<(String, PathBuf)> = Vec::new();

    if let Ok(dir) = fs::read_dir(&workspace_root) {
        for entry in dir.filter_map(|e| e.ok()) {
            let name = entry.file_name().into_string().unwrap_or_default();
            if (name.starts_with("historie-") && name.ends_with(".json")) || name == "stammdaten.json" {
                let abs_path = fs::canonicalize(entry.path()).unwrap_or_else(|_| entry.path());
                println!("cargo:rerun-if-changed={}", abs_path.display());
                entries.push((name, abs_path));
            }
        }
    }

    entries.sort_by(|a, b| a.0.cmp(&b.0));

    // Generate a Rust function that returns all embedded files.
    let mut code = String::from(
        "/// Auto-generated by build.rs: embedded JSON seed data.\n",
    );
    code.push_str("#[allow(dead_code)]\n");
    code.push_str("fn embedded_data_files() -> Vec<(&'static str, &'static str)> {\n");
    code.push_str("    vec![\n");
    for (name, path) in &entries {
        // Forward slashes work on all platforms inside include_str!().
        let path_str = path.display().to_string().replace('\\', "/");
        code.push_str(&format!(
            "        (\"{}\", include_str!(\"{}\")),\n",
            name, path_str
        ));
    }
    code.push_str("    ]\n");
    code.push_str("}\n");

    fs::write(&gen_path, &code).expect("Failed to write embedded_historie.rs");
}
